conversion_keys = {'adGroupAd ad id' : 'int64',
    'adGroup adRotationMode' : 'string',
    'adGroupAudienceView resourceName' : 'string',
    'adGroupCriterion criterionId' : 'int64',
    'adGroupCriterion keyword text' : 'string',
    'adGroupCriterion status' : 'string',
    'adGroup baseAdGroup' : 'string',
    'adGroup id' : 'int64',
    'biddingStrategy targetCpa targetCpaMicros' : 'int64',
    'biddingStrategy targetImpressionShare locationFractionMicros' : 'float',
    'biddingStrategy type' : 'string',
    'campaignAudienceView resourceName' : 'string',
    'campaignCriterion type' : 'string',
    'campaignCriterion adSchedule dayOfWeek' : 'string',
    'campaignCriterion device type' : 'string',      
    'campaignCriterion ageRange type' : 'string',
    'campaign advertisingChannelType' : 'string',
    'campaign biddingStrategyType' : 'string',
    'campaign campaignBudget' : 'string',
    'campaign geoTargetTypeSetting positiveGeoTargetType' : 'string',
    'campaign id' : 'int64',
    'campaign labels' : 'object', #campaign labels returns a list/array
    'campaign name' : 'string',
    'campaign status' : 'string',
    'customer id' : 'int64',
    'metrics allConversions' : 'int64',
    'metrics allConversionsValue' : 'float',
    'metrics bounceRate' : 'float',
    'metrics clicks' : 'int64',
    'metrics conversions' : 'int64',
    'metrics conversionsValue' : 'float',
    'metrics costMicros' : 'int64',
    'metrics costPerConversion' : 'int64',
    'metrics crossDeviceConversions' : 'int64',
    'metrics historicalCreativeQualityScore' : 'string',
    'metrics historicalLandingPageQualityScore' : 'string',
    'metrics historicalSearchPredictedCtr' : 'string',
    'metrics historicalQualityScore' : 'string',
    'metrics impressions' : 'int64',
    'metrics searchImpressionShare' : 'float',
    'metrics searchAbsoluteTopImressionShare' : 'float',
    'metrics searchRankLostImpressionShare' : 'float',
    'metrics searchBudgetLostImpressionShare' : 'float',
    'metrics searchClickShare' : 'float',
    'searchTermView searchTerm' : 'string',
    'searchTermView status' : 'string',
    'segments adNetworkType' : 'string',
    'segments device' : 'string',
    'segments geoTargetMostSpecificLocation' : 'string',
    'segments keyword info matchType' : 'string',
    'segments keyword info text' : 'string',
    'segments searchTermMatchType' : 'string',
    'segments week' : 'string',
    'userList name' : 'string',
    'userLocationView countryCriterionId' : 'int64',
    'userLocationView resourceName' : 'string',
    'userLocationView targetingLocation' : 'boolean',
    }
